#include <lib/gui/einput.h>
#include <lib/gui/elistbox.h>

	/* generated by parseactions.py - do not modify! */
struct eActionList
{
	const char *m_context, *m_action;
	int m_id;
} actions[]={
	// ../../lib/gui/einput.h
{"InputActions", "moveLeft", eInput::moveLeft},
{"InputActions", "moveRight", eInput::moveRight},
{"InputActions", "moveHome", eInput::moveHome},
{"InputActions", "moveEnd", eInput::moveEnd},
{"InputActions", "deleteForward", eInput::deleteForward},
{"InputActions", "deleteBackward", eInput::deleteBackward},
{"InputActions", "toggleOverwrite", eInput::toggleOverwrite},
{"InputActions", "accept", eInput::accept},
{"AsciiActions", "gotAsciiCode", eInput::gotAsciiCode},
	// ../../lib/gui/elistbox.h
{"ListboxActions", "moveUp", eListbox::moveUp},
{"ListboxActions", "moveDown", eListbox::moveDown},
{"ListboxActions", "moveTop", eListbox::moveTop},
{"ListboxActions", "moveEnd", eListbox::moveEnd},
{"ListboxActions", "pageUp", eListbox::pageUp},
{"ListboxActions", "pageDown", eListbox::pageDown},
{"ListboxActions", "justCheck", eListbox::justCheck},
};
